version: '3.3'
services:
  backend:
    ports:
      - "5000:5000"
    build:
      context: .
      args:
        - ARTIFACTORY_USERNAME=${ARTIFACTORY_USR}
        - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PSW}
    command: npm run start
    volumes:
      - ./src:/app/src:z
    networks:
      - zoom-family-network
networks:
  zoom-family-network:
    external:
      name: zoom-family-network